# DynamoDB table configurations
tables:
  - TableName: "Nathan_Alerts"
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: "alert_id"
        AttributeType: "S"
      - AttributeName: "timestamp"
        AttributeType: "N"
      - AttributeName: "status"  # New attribute for GSI
        AttributeType: "S"
    KeySchema:
      - AttributeName: "alert_id"
        KeyType: "HASH"
      - AttributeName: "timestamp"
        KeyType: "RANGE"
    GlobalSecondaryIndexes:  # New GSI definition
      - IndexName: "StatusIndex"
        KeySchema:
          - AttributeName: "status"
            KeyType: "HASH"
          - AttributeName: "timestamp"
            KeyType: "RANGE"
        Projection:
          ProjectionType: "ALL"
    SSESpecification:
      SSEEnabled: true
  - TableName: "Nathan_Runbooks"
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: "runbook_id"
        AttributeType: "S"
      - AttributeName: "last_updated"
        AttributeType: "N"
    KeySchema:
      - AttributeName: "runbook_id"
        KeyType: "HASH"
      - AttributeName: "last_updated"
        KeyType: "RANGE"
    SSESpecification:
      SSEEnabled: true
  - TableName: "Nathan_Analytics"
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: "event_id"
        AttributeType: "S"
      - AttributeName: "event_timestamp"
        AttributeType: "N"
    KeySchema:
      - AttributeName: "event_id"
        KeyType: "HASH"
      - AttributeName: "event_timestamp"
        KeyType: "RANGE"
    SSESpecification:
      SSEEnabled: true
  - TableName: "NOC_Stats"
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: "engineer_id"
        AttributeType: "S"
      - AttributeName: "response_timestamp"
        AttributeType: "N"
    KeySchema:
      - AttributeName: "engineer_id"
        KeyType: "HASH"
      - AttributeName: "response_timestamp"
        KeyType: "RANGE"
    SSESpecification:
      SSEEnabled: true
