# Nathan's AWS Lambda Environment Variables

# Environment variables for Nathan Lambda function
environment:
  GITLAB_API_ENDPOINT: "https://gitlab.com/api/v4/projects/123456/repository/files/"
  GITLAB_TOKEN: "your_gitlab_access_token"
  OPENAI_API_KEY: "your_openai_api_key"
  SLACK_API_TOKEN: "your_slack_api_token"
  SLACK_CHANNEL: "#alerts"
  SLACK_BOT_USER: "NathanBot"
  ALERT_RESOLVE_TIMEOUT: "600" # 10 minutes in seconds
  AWS_REGION: "us-west-2"  # Updated to match the DynamoDB and Lambda configuration
  AWS_S3_BUCKET: "nathan-lambda-deployment-bucket"
  RUNBOOK_SYNC_INTERVAL: "3600" # 1 hour in seconds
  DYNAMODB_REGION: "us-west-2"  # Added for DynamoDB client initialization
  ALERTS_TABLE_NAME: "Nathan_Alerts"  # Added for DynamoDB alerts table
  RUNBOOKS_TABLE_NAME: "Nathan_Runbooks"  # Added for DynamoDB runbooks table
  ANALYTICS_TABLE_NAME: "Nathan_Analytics"  # Added for DynamoDB analytics table
  ALERTS_CHANNEL_ID: "SLACK_CHANNEL_ID_FOR_ALERTS"  # Added for Slack alerts channel ID
  
# Miscellaneous
LOG_LEVEL: "INFO"  # The logging level. Options: DEBUG, INFO, WARNING, ERROR, CRITICAL.
MAX_RESPONSE_TIME: 300  # Maximum time (in seconds) allowed for Nathan to respond to an alert.

# Any other environment-specific configurations you need for your project can be added here.
